title: Hyperbee Json
description: Documentation for Hyperbee Json.
remote_theme: pmarsceill/just-the-docs
baseurl: "/hyperbee.json/" 
url: "https://stillpoint-software.github.io"

aux_links:
  "GitHub Repository":
    - "//github.com/Stillpoint-Software/hyperbee.json"

footer_content: |
  <footer class="site-footer">
    <p>&copy; <span id="copyright-year"></span> <a href='https://www.stillpointsoftware.net/'>Stillpoint Software</a>. All rights reserved.</p>
    <script>
      document.getElementById("copyright-year").textContent = new Date().getFullYear();
    </script>
  </footer>

# logo: "/assets/icon.png"
search_enabled: true # Enable search

# External navigation links
nav_external_links:
  - title: Stillpoint Software
    url: https://www.stillpointsoftware.net/
    opens_in_new_tab: true
