title: Hyperbee Json
description: Documentation for Hyperbee Json.
remote_theme: pmarsceill/just-the-docs

aux_links:
  "GitHub Repository":
    - "//github.com/Stillpoint-Software/hyperbee.json"

logo: "/assets/icon.png"
search_enabled: true # Enable search
